// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutSchool: typeof import('./src/components/AboutSchool.vue')['default']
    AboutUs: typeof import('./src/components/AboutUs.vue')['default']
    ApplicationForm: typeof import('./src/components/ApplicationForm.vue')['default']
    ApplicationFormCard: typeof import('./src/components/ApplicationFormCard.vue')['default']
    ArrowIcon: typeof import('./src/components/icons/ArrowIcon.vue')['default']
    ArrowWhite: typeof import('./src/components/icons/ArrowWhite.vue')['default']
    CarouselInfo: typeof import('./src/components/CarouselInfo.vue')['default']
    ConnectButton: typeof import('./src/components/ConnectButton.vue')['default']
    DownIcon: typeof import('./src/components/icons/DownIcon.vue')['default']
    Facebook: typeof import('./src/components/icons/Facebook.vue')['default']
    Footer: typeof import('./src/components/layouts/Footer.vue')['default']
    FooterCard: typeof import('./src/components/FooterCard.vue')['default']
    Header: typeof import('./src/components/layouts/Header.vue')['default']
    HeaderCard: typeof import('./src/components/HeaderCard.vue')['default']
    ImageInfo: typeof import('./src/components/ImageInfo.vue')['default']
    Instagram: typeof import('./src/components/icons/Instagram.vue')['default']
    Modal: typeof import('./src/components/layouts/Modal.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NewsZerdeCard: typeof import('./src/components/NewsZerdeCard.vue')['default']
    PartnersCard: typeof import('./src/components/PartnersCard.vue')['default']
    QuestionsCard: typeof import('./src/components/QuestionsCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchoolAdvances: typeof import('./src/components/SchoolAdvances.vue')['default']
    SchoolGoalsCard: typeof import('./src/components/SchoolGoalsCard.vue')['default']
    SchoolHistory: typeof import('./src/components/SchoolHistory.vue')['default']
    SchoolValuesCard: typeof import('./src/components/SchoolValuesCard.vue')['default']
    SendButton: typeof import('./src/components/SendButton.vue')['default']
    Whatsapp: typeof import('./src/components/icons/Whatsapp.vue')['default']
    Youtube: typeof import('./src/components/icons/Youtube.vue')['default']
  }
}

export { }
