// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutSchool: typeof import('./src/components/AboutSchool.vue')['default']
    AboutUs: typeof import('./src/components/AboutUs.vue')['default']
    ApplicationForm: typeof import('./src/components/ApplicationForm.vue')['default']
    ArrowIcon: typeof import('./src/components/icons/ArrowIcon.vue')['default']
    CarouselInfo: typeof import('./src/components/CarouselInfo.vue')['default']
    DownIcon: typeof import('./src/components/icons/DownIcon.vue')['default']
    Footer: typeof import('./src/components/layouts/Footer.vue')['default']
    Header: typeof import('./src/components/layouts/Header.vue')['default']
    ImageInfo: typeof import('./src/components/ImageInfo.vue')['default']
    Modal: typeof import('./src/components/layouts/Modal.vue')['default']
    NewsZerdeCard: typeof import('./src/components/NewsZerdeCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchoolAdvances: typeof import('./src/components/SchoolAdvances.vue')['default']
    SchoolHistory: typeof import('./src/components/SchoolHistory.vue')['default']
    SchoolValuesCard: typeof import('./src/components/SchoolValuesCard.vue')['default']
  }
}

export { }
